name: Build GBA ROM


on:
push:
branches: [ main, master ]
pull_request:
workflow_dispatch:


jobs:
build:
runs-on: ubuntu-latest
container: devkitpro/devkitarm:latest
steps:
- name: Checkout
uses: actions/checkout@v4


- name: Fetch Butano
run: |
git clone --depth 1 https://github.com/GValiente/butano.git third_party/butano


- name: Install tools (python, pip, unzip)
run: |
apt-get update
apt-get install -y python3 python3-pip unzip ca-certificates
python3 -m pip install --upgrade pip
pip3 install pillow requests


- name: Fetch + convert assets
run: |
python3 tools/fetch_assets.py


- name: Build ROM
env:
LIBBUTANO: ${{ github.workspace }}/third_party/butano/butano
run: |
make -j2


- name: Upload artifact
uses: actions/upload-artifact@v4
with:
name: PuffQuestAdvance.gba
path: PuffQuestAdvance.gba
