name: Build GBA ROM

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Install Python from the distro (no pip – avoids PEP 668 issues)
      - name: Install Python deps
        run: >
          apt-get update &&
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends
          python3 python3-pil python3-requests git ca-certificates &&
          python3 -c "import PIL,requests; print('Python deps OK')"

      # Fetch Butano into third_party/butano
      - name: Fetch Butano
        run: |
          rm -rf third_party/butano
          git clone --depth 1 --branch master https://github.com/GValiente/butano.git third_party/butano

      # Generate local placeholder assets (no network)
      - name: Fetch + convert assets
        run: python3 tools/fetch_assets.py

      # Build ROM (point Make to butano.mak explicitly)
      - name: Build ROM
        run: make -j2 LIBBUTANO="$GITHUB_WORKSPACE/third_party/butano/butano"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PuffQuestAdvance.gba
          path: PuffQuestAdvance.gba
