name: Build GBA ROM


on:
push:
branches: [ "main", "master" ]
pull_request:
workflow_dispatch:


jobs:
build:
runs-on: ubuntu-latest
container:
image: devkitpro/devkitarm:latest
steps:
- name: Checkout
uses: actions/checkout@v4


- name: Install Python + pip (inside container)
run: |
if ! command -v python3 >/dev/null 2>&1; then
pacman -Sy --noconfirm python python-pip
fi
python3 -m pip install --upgrade pip
pip3 install pillow requests


- name: Fetch Butano
run: |
git clone --depth 1 https://github.com/GValiente/butano.git third_party/butano


- name: Fetch + convert assets
run: |
python3 tools/fetch_assets.py


- name: Build ROM
env:
LIBBUTANO: ${{ github.workspace }}/third_party/butano/butano
run: make -j2


- name: Upload artifact
uses: actions/upload-artifact@v4
with:
name: PuffQuestAdvance.gba
path: PuffQuestAdvance.gba
