name: Build GBA ROM

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Install Python + deps from the distro to avoid pip PEP 668 issues
      - name: Install Python deps
        run: apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends python3 python3-pip python3-pil python3-requests git ca-certificates

      - name: Fetch Butano
        run: git clone --depth 1 https://github.com/GValiente/butano.git third_party/butano

      - name: Fetch + convert assets
        run: python3 tools/fetch_assets.py

      - name: Build ROM
        env:
          LIBBUTANO: ${{ github.workspace }}/third_party/butano/butano
        run: make -j2

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PuffQuestAdvance.gba
          path: PuffQuestAdvance.gba
