name: Build GBA ROM

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: python -m pip install --upgrade pip && pip install pillow requests

      - name: Fetch Butano
        uses: actions/checkout@v4
        with:
          repository: GValiente/butano
          path: third_party/butano
          fetch-depth: 1

      - name: Fetch + convert assets
        run: python3 tools/fetch_assets.py

      - name: Build ROM
        env:
          LIBBUTANO: ${{ github.workspace }}/third_party/butano/butano
        run: make -j2

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PuffQuestAdvance.gba
          path: PuffQuestAdvance.gba
