name: Build GBA ROM

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Install Python + deps from the distro (no pip; avoids PEP 668)
      - name: Install Python deps
        run: apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends python3 python3-pil python3-requests git ca-certificates && python3 -c "import PIL,requests; print('Python deps OK')"

      # Pull Butano into third_party/butano
      - name: Fetch Butano
        uses: actions/checkout@v4
        with:
          repository: GValiente/butano
          path: third_party/butano
          fetch-depth: 1

      # Generate local placeholder assets (no network)
      - name: Fetch + convert assets
        run: python3 tools/fetch_assets.py

      - name: Build ROM
        run: make -j2

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PuffQuestAdvance.gba
          path: PuffQuestAdvance.gba
