name: Build GBA ROM

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Install Python from the distro (no pip – avoids PEP 668 issues)
      - name: Install Python deps
        run: apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends python3 python3-pil python3-requests git ca-certificates && python3 -c "import PIL,requests; print('Python deps OK')"

      # Fetch Butano into third_party/butano
      - name: Fetch Butano
        run: |
          rm -rf third_party/butano
          git clone --depth 1 --branch master https://github.com/GValiente/butano.git third_party/butano

      # Generate local placeholder assets (no network)
      - name: Fetch + convert assets
        run: python3 tools/fetch_assets.py

      # Build ROM with explicit devkitPro env so Butano can find its tool includes
      - name: Build ROM
        env:
          DEVKITPRO: /opt/devkitpro
          DEVKITARM: /opt/devkitpro/devkitARM
          PATH: /opt/devkitpro/devkitARM/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          LIBBUTANO: ${{ github.workspace }}/third_party/butano/butano
        run: make -j2

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PuffQuestAdvance.gba
          path: PuffQuestAdvance.gba
